[package]
name = "aarambh-studio-finetune"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true

[features]
default = []
cuda = [
    "aarambh-studio-audio/cuda",
    "aarambh-studio-core/cuda",
    "aarambh-studio-kernel/cuda",
    "aarambh-studio-model/cuda",
    "aarambh-studio-nn/cuda",
    "aarambh-studio-quant/cuda",
    "aarambh-studio-train/cuda",
    "aarambh-studio-vision/cuda",
    "aarambh-studio-weights/cuda",
    "candle-core/cuda",
    "candle-nn/cuda",
]

[dependencies]
aarambh-studio-audio     = { path = "../aarambh-studio-audio" }
aarambh-studio-core      = { path = "../aarambh-studio-core" }
aarambh-studio-kernel    = { path = "../aarambh-studio-kernel" }
aarambh-studio-model     = { path = "../aarambh-studio-model" }
aarambh-studio-nn        = { path = "../aarambh-studio-nn" }
aarambh-studio-quant     = { path = "../aarambh-studio-quant" }
aarambh-studio-tokenizer = { path = "../aarambh-studio-tokenizer" }
aarambh-studio-train     = { path = "../aarambh-studio-train" }
aarambh-studio-vision    = { path = "../aarambh-studio-vision" }
aarambh-studio-weights   = { path = "../aarambh-studio-weights" }
candle-core          = { workspace = true }
candle-nn            = { workspace = true }
rand                 = "0.8"
serde                = { workspace = true }
serde_json           = { workspace = true }
