use std::fs::{self, OpenOptions};
use std::io::{BufWriter, Write};
use std::path::{Path, PathBuf};
use std::time::Instant;

use aarambh_studio_core::{
    AarambhError, Configurable, DType, Device, ModelConfig, Result, TokenizerLike, TrainConfig,
};
use aarambh_studio_inference::InferenceEngine;
use aarambh_studio_model::AarambhModel;
use aarambh_studio_tokenizer::{BpeTokenizer, PAD_ID};
use aarambh_studio_train::optim::clip_gradients;
use aarambh_studio_train::{
    AdamW, AdamWConfig, CosineScheduleWithWarmup, DsaTrainingConfig, GradMap, combine_mtp_losses,
    mtp_head_loss,
};
use candle_core::Tensor;
use candle_core::backprop::GradStore;
use candle_nn::{VarBuilder, VarMap};
use rand::SeedableRng;
use rand::rngs::StdRng;
use rand::seq::SliceRandom;
use serde::{Deserialize, Serialize};

use crate::checkpoint::{DistillCheckpointManager, DistillState};
use crate::config::{DistillConfig, DistillObjective};
use crate::dataset::{PromptDataset, ReplayBatch, ScoredReferenceDataset};
use crate::distill_loss::{reward_policy_loss, soft_kl_loss};
use crate::rollout::{StudentRollout, generate_student_rollouts};
use crate::teacher_score::{
    LocalCheckpointTeacher, ScoredDatasetTeacher, TeacherScorer, TeacherSignal,
};

/// Frozen teacher selected for one distillation run.
#[derive(Debug, Clone)]
pub enum TeacherSourceConfig {
    /// A larger local Aarambh checkpoint.
    Local {
        /// Teacher checkpoint path.
        model_path: PathBuf,
        /// Teacher architecture configuration.
        model_config: Box<ModelConfig>,
        /// Teacher compute device.
        device: Device,
        /// Teacher parameter dtype.
        dtype: DType,
    },
    /// A low-memory scored-reference JSONL dataset.
    Dataset {
        /// Scored-reference JSONL path.
        data_path: PathBuf,
    },
}

impl TeacherSourceConfig {
    fn identifier(&self) -> String {
        match self {
            Self::Local { model_path, .. } => model_path.display().to_string(),
            Self::Dataset { data_path } => data_path.display().to_string(),
        }
    }
}

/// Complete configuration for full-weight on-policy distillation.
#[derive(Debug, Clone)]
pub struct DistillRunConfig {
    /// Student architecture configuration.
    pub model_config: ModelConfig,
    /// Optimizer and checkpoint cadence.
    pub train_config: TrainConfig,
    /// DSA indexer teacher cadence and weight.
    pub dsa_training_config: DsaTrainingConfig,
    /// Rollout and objective settings.
    pub distill_config: DistillConfig,
    /// Trainable student SafeTensors checkpoint.
    pub student_model_path: PathBuf,
    /// Shared tokenizer JSON path.
    pub tokenizer_path: PathBuf,
    /// Prompt JSONL path.
    pub prompt_path: PathBuf,
    /// Output checkpoint directory.
    pub output_dir: PathBuf,
    /// Student compute device.
    pub device: Device,
    /// Student parameter dtype.
    pub dtype: DType,
    /// Frozen teacher backend.
    pub teacher: TeacherSourceConfig,
    /// Whether prompt order is shuffled each epoch.
    pub shuffle: bool,
    /// Whether to restore the latest output checkpoint.
    pub resume: bool,
}

/// Metrics emitted after a distillation optimizer update.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistillMetrics {
    /// Completed optimizer step.
    pub step: usize,
    /// Combined distillation and architecture-auxiliary loss.
    pub loss: f64,
    /// Unweighted KL or reward-policy loss.
    pub distill_loss: f64,
    /// Mean scalar teacher reward.
    pub reward_mean: f64,
    /// Standard deviation of scalar teacher rewards.
    pub reward_std: f64,
    /// Mean group-normalized advantage for reward training.
    pub advantage_mean: Option<f64>,
    /// Teacher-student forward KL when soft targets are active.
    pub teacher_student_kl: Option<f64>,
    /// Unweighted mean MTP auxiliary loss.
    pub mtp_aux_loss: Option<f64>,
    /// Per-offset MTP losses.
    pub mtp_head_losses: Vec<(usize, f64)>,
    /// Unweighted MoE balancing loss.
    pub moe_aux_loss: Option<f64>,
    /// Periodic DSA indexer loss.
    pub dsa_indexer_loss: Option<f64>,
    /// Learning rate used for this update.
    pub lr: f64,
    /// Global gradient norm before clipping.
    pub grad_norm: f64,
    /// Student completion tokens generated by this micro-batch.
    pub rollout_tokens: usize,
    /// Student rollout throughput including scoring and replay.
    pub rollout_tokens_per_second: f64,
    /// Mean generated completion length.
    pub mean_completion_tokens: f64,
}

/// Full-weight on-policy distillation trainer.
pub struct DistillTrainer {
    engine: InferenceEngine,
    varmap: VarMap,
    optimizer: AdamW,
    schedule: CosineScheduleWithWarmup,
    scorer: Box<dyn TeacherScorer>,
    prompts: PromptDataset,
    train_config: TrainConfig,
    dsa_training_config: DsaTrainingConfig,
    distill_config: DistillConfig,
    checkpoint: DistillCheckpointManager,
    manifest: serde_json::Value,
    state: DistillState,
    pending_grads: GradMap,
    shuffle: bool,
    seed: u64,
    metrics_path: PathBuf,
}

impl DistillTrainer {
    #[allow(clippy::too_many_arguments)]
    /// Construct a trainer from a trainable student and frozen teacher scorer.
    pub fn new(
        engine: InferenceEngine,
        varmap: VarMap,
        scorer: Box<dyn TeacherScorer>,
        prompts: PromptDataset,
        train_config: TrainConfig,
        dsa_training_config: DsaTrainingConfig,
        distill_config: DistillConfig,
        output_dir: impl Into<PathBuf>,
        manifest: serde_json::Value,
        shuffle: bool,
    ) -> Result<Self> {
        distill_config.validate()?;
        dsa_training_config.validate()?;
        if train_config.batch_size == 0
            || train_config.grad_accum_steps == 0
            || train_config.max_steps == 0
            || train_config.max_epochs == 0
        {
            return Err(AarambhError::Config(
                "distillation batch, accumulation, step, and epoch limits must be non-zero".into(),
            ));
        }
        if prompts.is_empty() {
            return Err(AarambhError::Config(
                "distillation prompt dataset is empty".into(),
            ));
        }
        let optimizer = AdamW::from_varmap(&varmap, AdamWConfig::from(&train_config))?;
        if optimizer.parameters().is_empty() {
            return Err(AarambhError::Config(
                "distillation student has no trainable parameters".into(),
            ));
        }
        let schedule = CosineScheduleWithWarmup::from_train_config(&train_config);
        let output_dir = output_dir.into();
        let seed = train_config.seed;
        let mut trainer = Self {
            engine,
            varmap,
            optimizer,
            schedule,
            scorer,
            prompts,
            train_config,
            dsa_training_config,
            distill_config,
            checkpoint: DistillCheckpointManager::new(&output_dir),
            manifest,
            state: DistillState::default(),
            pending_grads: GradMap::new(),
            shuffle,
            seed,
            metrics_path: output_dir.join("metrics.jsonl"),
        };
        trainer.reset_prompt_order();
        Ok(trainer)
    }

    /// Return the current resumable state.
    pub fn state(&self) -> &DistillState {
        &self.state
    }

    /// Return the trainable student model.
    pub fn model(&self) -> &AarambhModel {
        self.engine.model()
    }

    /// Restore the latest checkpoint if one exists.
    pub fn load_latest_checkpoint(&mut self) -> Result<bool> {
        match self.checkpoint.load_latest(
            &mut self.varmap,
            &mut self.optimizer,
            &self.manifest,
            self.engine.device(),
        )? {
            Some(state) => {
                validate_state(&state, self.prompts.len())?;
                self.state = state;
                Ok(true)
            }
            None => Ok(false),
        }
    }

    /// Run the complete on-policy distillation loop and save a final checkpoint.
    pub fn train(&mut self) -> Result<()> {
        while self.state.epoch < self.train_config.max_epochs
            && self.state.step < self.train_config.max_steps
        {
            let prompt_batch = self.next_prompt_batch();
            if prompt_batch.is_empty() {
                self.flush_pending_step()?;
                self.state.epoch += 1;
                if self.state.epoch < self.train_config.max_epochs {
                    self.reset_prompt_order();
                }
                continue;
            }
            let started = Instant::now();
            let rollouts = generate_student_rollouts(
                &self.engine,
                &prompt_batch,
                &self.distill_config,
                self.state.step,
                self.seed,
            )?;
            let metrics = self.train_rollouts(&rollouts, started.elapsed().as_secs_f64())?;
            if let Some(metrics) = metrics {
                self.after_optimizer_step(&metrics)?;
            }
        }
        self.flush_pending_step()?;
        self.checkpoint
            .save_final(&self.varmap, &self.optimizer, &self.state, &self.manifest)?;
        Ok(())
    }

    /// Replay one freshly generated rollout batch and optionally update the optimizer.
    pub fn train_rollouts(
        &mut self,
        rollouts: &[StudentRollout],
        rollout_seconds: f64,
    ) -> Result<Option<DistillMetrics>> {
        if self.distill_config.objective == DistillObjective::Reward {
            validate_reward_groups(rollouts, self.distill_config.rollouts_per_prompt)?;
        }
        let replay = ReplayBatch::from_rollouts(rollouts, PAD_ID, self.engine.device())?;
        let signal = match self.distill_config.objective {
            DistillObjective::SoftKl => TeacherSignal::SoftLogits,
            DistillObjective::Reward => TeacherSignal::Reward,
        };
        let feedback = self.scorer.score_batch(rollouts, &replay, signal)?;
        if feedback.scores.len() != rollouts.len() {
            return Err(AarambhError::Shape(
                "teacher returned the wrong number of rollout scores".into(),
            ));
        }
        let scores = feedback
            .scores
            .iter()
            .map(|score| score.reward)
            .collect::<Vec<_>>();

        let collect_dsa_teacher = self.engine.model().config().dsa_config.is_some()
            && self
                .state
                .step
                .is_multiple_of(self.dsa_training_config.teacher_every_n_steps);
        let output = self
            .engine
            .model()
            .forward_train_with_aux_and_dsa_teacher(&replay.input_ids, collect_dsa_teacher)?;
        let packed_student_logits = replay.pack_logits(&output.logits)?;
        let (distill_loss, advantages, teacher_student_kl) = match self.distill_config.objective {
            DistillObjective::SoftKl => {
                let teacher_logits = feedback.packed_logits.as_ref().ok_or_else(|| {
                    AarambhError::Config("soft-KL teacher returned no token logits".into())
                })?;
                let result = soft_kl_loss(
                    &packed_student_logits,
                    teacher_logits,
                    self.distill_config.teacher_temperature,
                )?;
                let value = result.loss.to_scalar::<f32>()? as f64;
                (result.loss, None, Some(value))
            }
            DistillObjective::Reward => {
                let result = reward_policy_loss(
                    &packed_student_logits,
                    &replay.packed_labels()?,
                    &replay.completion_counts,
                    &scores,
                    self.distill_config.rollouts_per_prompt,
                    self.distill_config.advantage_clip,
                )?;
                (result.loss, Some(result.advantages), None)
            }
        };
        let distill_loss_value = distill_loss.to_scalar::<f32>()? as f64;

        let mut mtp_losses = Vec::with_capacity(self.engine.model().mtp_heads().len());
        for head_index in 0..self.engine.model().mtp_heads().len() {
            let prediction = self.engine.model().forward_mtp_head_train(
                head_index,
                &output.final_hidden_states,
                &replay.input_ids,
            )?;
            mtp_losses.push(mtp_head_loss(
                prediction,
                &replay.labels,
                &replay.completion_mask,
            )?);
        }
        let mtp_weight = self
            .engine
            .model()
            .config()
            .mtp
            .as_ref()
            .map(|config| config.aux_loss_weight)
            .unwrap_or(0.0);
        let mtp = combine_mtp_losses(distill_loss, mtp_losses, mtp_weight)?;
        let mut loss = mtp.total_loss.clone();
        let moe_weight = self
            .engine
            .model()
            .config()
            .moe
            .as_ref()
            .map(|config| config.aux_loss_weight)
            .unwrap_or(0.0);
        if let Some(moe_loss) = &output.moe_aux_loss
            && moe_weight > 0.0
        {
            loss = (&loss + &moe_loss.affine(moe_weight, 0.0)?)?;
        }
        if let Some(dsa_loss) = &output.dsa_indexer_loss
            && self.dsa_training_config.indexer_loss_weight > 0.0
        {
            loss =
                (&loss + &dsa_loss.affine(self.dsa_training_config.indexer_loss_weight, 0.0)?)?;
        }
        let loss_value = loss.to_scalar::<f32>()? as f64;
        if !loss_value.is_finite() || !distill_loss_value.is_finite() {
            return Err(AarambhError::Config(format!(
                "non-finite distillation loss: total={loss_value} objective={distill_loss_value}"
            )));
        }

        let scaled = loss.affine(1.0 / self.train_config.grad_accum_steps as f64, 0.0)?;
        let grads = scaled.backward()?;
        self.accumulate_gradients(&grads)?;
        self.state.micro_step += 1;
        self.state.train_loss = Some(loss_value);
        self.state.rollout_tokens += replay.completion_tokens();

        if !self
            .state
            .micro_step
            .is_multiple_of(self.train_config.grad_accum_steps)
        {
            return Ok(None);
        }
        let (lr, grad_norm) = self.optimizer_step()?;
        let reward_mean = mean(&scores);
        let reward_std = stddev(&scores, reward_mean as f32);
        let advantage_mean = advantages.as_ref().map(|values| mean(values));
        let mtp_aux_loss = mtp
            .auxiliary_loss
            .as_ref()
            .map(|loss| loss.to_scalar::<f32>().map(|value| value as f64))
            .transpose()?;
        let mtp_head_losses = mtp
            .head_losses
            .iter()
            .map(|head| Ok((head.offset, head.loss.to_scalar::<f32>()? as f64)))
            .collect::<Result<Vec<_>>>()?;
        let moe_aux_loss = scalar_option(output.moe_aux_loss.as_ref())?;
        let dsa_indexer_loss = scalar_option(output.dsa_indexer_loss.as_ref())?;
        let elapsed = rollout_seconds.max(f64::EPSILON);
        Ok(Some(DistillMetrics {
            step: self.state.step,
            loss: loss_value,
            distill_loss: distill_loss_value,
            reward_mean,
            reward_std,
            advantage_mean,
            teacher_student_kl,
            mtp_aux_loss,
            mtp_head_losses,
            moe_aux_loss,
            dsa_indexer_loss,
            lr,
            grad_norm,
            rollout_tokens: replay.completion_tokens(),
            rollout_tokens_per_second: replay.completion_tokens() as f64 / elapsed,
            mean_completion_tokens: replay.completion_tokens() as f64 / rollouts.len() as f64,
        }))
    }

    fn next_prompt_batch(&mut self) -> Vec<crate::dataset::PromptExample> {
        if self.state.prompt_position >= self.state.prompt_order.len() {
            return Vec::new();
        }
        let end = (self.state.prompt_position + self.train_config.batch_size)
            .min(self.state.prompt_order.len());
        let batch = self.state.prompt_order[self.state.prompt_position..end]
            .iter()
            .map(|index| self.prompts.examples()[*index].clone())
            .collect();
        self.state.prompt_position = end;
        batch
    }

    fn reset_prompt_order(&mut self) {
        self.state.prompt_position = 0;
        self.state.prompt_order = (0..self.prompts.len()).collect();
        if self.shuffle {
            let mut rng =
                StdRng::seed_from_u64(self.seed ^ (self.state.epoch as u64).rotate_left(29));
            self.state.prompt_order.shuffle(&mut rng);
        }
    }

    fn accumulate_gradients(&mut self, grads: &GradStore) -> Result<()> {
        let mut updates = Vec::new();
        for parameter in self.optimizer.parameters() {
            let Some(gradient) = grads.get(parameter.tensor()) else {
                continue;
            };
            let gradient = gradient.detach();
            let accumulated = match self.pending_grads.get(parameter.name()) {
                Some(existing) => ((existing + &gradient)?).detach(),
                None => gradient,
            };
            updates.push((parameter.name().to_string(), accumulated));
        }
        if updates.is_empty() {
            return Err(AarambhError::Config(
                "distillation backward produced no student gradients".into(),
            ));
        }
        self.pending_grads.extend(updates);
        Ok(())
    }

    fn optimizer_step(&mut self) -> Result<(f64, f64)> {
        let lr = self.schedule.lr_at_step(self.state.step);
        let grad_norm = clip_gradients(&mut self.pending_grads, self.train_config.clip_grad_norm)?;
        self.optimizer.step(&self.pending_grads, lr)?;
        self.pending_grads.clear();
        self.state.step += 1;
        Ok((lr, grad_norm))
    }

    fn flush_pending_step(&mut self) -> Result<()> {
        if self.pending_grads.is_empty() || self.state.step >= self.train_config.max_steps {
            return Ok(());
        }
        let _ = self.optimizer_step()?;
        if self.train_config.save_every_n_steps > 0 {
            self.checkpoint
                .save(&self.varmap, &self.optimizer, &self.state, &self.manifest)?;
        }
        Ok(())
    }

    fn after_optimizer_step(&self, metrics: &DistillMetrics) -> Result<()> {
        if self.train_config.log_every_n_steps > 0
            && metrics
                .step
                .is_multiple_of(self.train_config.log_every_n_steps)
        {
            println!(
                "distill step={} loss={:.4} objective={:.4} reward={:.4}±{:.4} kl={:.5} lr={:.6} grad_norm={:.4} tok/s={:.2}",
                metrics.step,
                metrics.loss,
                metrics.distill_loss,
                metrics.reward_mean,
                metrics.reward_std,
                metrics.teacher_student_kl.unwrap_or(0.0),
                metrics.lr,
                metrics.grad_norm,
                metrics.rollout_tokens_per_second,
            );
        }
        append_jsonl(&self.metrics_path, metrics)?;
        if self.train_config.save_every_n_steps > 0
            && metrics
                .step
                .is_multiple_of(self.train_config.save_every_n_steps)
        {
            self.checkpoint
                .save(&self.varmap, &self.optimizer, &self.state, &self.manifest)?;
        }
        Ok(())
    }
}

/// Build and execute an on-policy distillation run from paths and configs.
pub fn run_distill_from_config(mut config: DistillRunConfig) -> Result<()> {
    config.distill_config.validate()?;
    config.dsa_training_config.validate()?;
    if config
        .student_model_path
        .extension()
        .and_then(|value| value.to_str())
        != Some("safetensors")
    {
        return Err(AarambhError::Config(
            "the trainable distillation student must be a SafeTensors checkpoint".into(),
        ));
    }
    if matches!(config.teacher, TeacherSourceConfig::Dataset { .. })
        && config.distill_config.objective != DistillObjective::Reward
    {
        return Err(AarambhError::Config(
            "scored-reference teachers require --objective reward".into(),
        ));
    }
    let device = config.device.to_candle()?;
    let dtype = config.dtype.to_candle();
    let tokenizer = BpeTokenizer::from_pretrained(&config.tokenizer_path)?;
    tokenizer.validate_special_tokens()?;
    config.model_config.vocab_size = tokenizer.vocab_size();
    AarambhModel::validate_config(&config.model_config)?;

    let mut varmap = VarMap::new();
    let student = AarambhModel::new(
        &config.model_config,
        VarBuilder::from_varmap(&varmap, dtype, &device),
    )?;
    varmap.load(&config.student_model_path)?;
    let engine = InferenceEngine::new(student, tokenizer.clone(), device.clone())?;
    let prompts = PromptDataset::from_jsonl(&config.prompt_path)?;

    let scorer: Box<dyn TeacherScorer> = match &mut config.teacher {
        TeacherSourceConfig::Local {
            model_path,
            model_config,
            device: teacher_device,
            dtype: teacher_dtype,
        } => {
            model_config.vocab_size = tokenizer.vocab_size();
            AarambhModel::validate_config(model_config)?;
            if model_config.vocab_size != config.model_config.vocab_size {
                return Err(AarambhError::Config(
                    "student and teacher vocabularies must match".into(),
                ));
            }
            Box::new(LocalCheckpointTeacher::from_paths(
                model_path,
                model_config,
                teacher_device.to_candle()?,
                teacher_dtype.to_candle(),
            )?)
        }
        TeacherSourceConfig::Dataset { data_path } => {
            let dataset = ScoredReferenceDataset::from_jsonl(data_path)?;
            dataset.validate_prompt_coverage(&prompts)?;
            Box::new(ScoredDatasetTeacher::new(dataset, tokenizer.clone())?)
        }
    };
    let manifest = manifest(&config, scorer.backend_name())?;
    fs::create_dir_all(&config.output_dir)?;
    let mut trainer = DistillTrainer::new(
        engine,
        varmap,
        scorer,
        prompts,
        config.train_config,
        config.dsa_training_config,
        config.distill_config,
        config.output_dir,
        manifest,
        config.shuffle,
    )?;
    if config.resume && !trainer.load_latest_checkpoint()? {
        return Err(AarambhError::Checkpoint(
            "distillation resume requested but no latest checkpoint exists".into(),
        ));
    }
    trainer.train()
}

fn manifest(config: &DistillRunConfig, backend: &str) -> Result<serde_json::Value> {
    Ok(serde_json::json!({
        "schema_version": 1,
        "student_model": config.student_model_path.display().to_string(),
        "student_model_config": config.model_config,
        "tokenizer": config.tokenizer_path.display().to_string(),
        "prompt_dataset": config.prompt_path.display().to_string(),
        "teacher_backend": backend,
        "teacher_identifier": config.teacher.identifier(),
        "distill": config.distill_config,
        "train": config.train_config,
        "dsa_training": config.dsa_training_config,
        "shuffle": config.shuffle,
    }))
}

fn validate_state(state: &DistillState, prompt_count: usize) -> Result<()> {
    if state.prompt_position > state.prompt_order.len()
        || state.prompt_order.len() != prompt_count
        || state
            .prompt_order
            .iter()
            .any(|index| *index >= prompt_count)
    {
        return Err(AarambhError::Checkpoint(
            "distillation checkpoint has an invalid prompt cursor or order".into(),
        ));
    }
    let mut sorted = state.prompt_order.clone();
    sorted.sort_unstable();
    if sorted != (0..prompt_count).collect::<Vec<_>>() {
        return Err(AarambhError::Checkpoint(
            "distillation checkpoint prompt order is not a permutation".into(),
        ));
    }
    Ok(())
}

fn validate_reward_groups(rollouts: &[StudentRollout], group_size: usize) -> Result<()> {
    if group_size < 2 || rollouts.is_empty() || !rollouts.len().is_multiple_of(group_size) {
        return Err(AarambhError::Config(
            "reward distillation requires complete prompt rollout groups".into(),
        ));
    }
    for group in rollouts.chunks(group_size) {
        let prompt_id = &group[0].prompt_id;
        let mut indexes = group
            .iter()
            .map(|rollout| {
                if &rollout.prompt_id != prompt_id {
                    return Err(AarambhError::Config(
                        "reward rollout groups cannot mix prompt ids".into(),
                    ));
                }
                Ok(rollout.rollout_index)
            })
            .collect::<Result<Vec<_>>>()?;
        indexes.sort_unstable();
        if indexes != (0..group_size).collect::<Vec<_>>() {
            return Err(AarambhError::Config(
                "reward rollout indexes must be unique and contiguous within each prompt group"
                    .into(),
            ));
        }
    }
    Ok(())
}

fn append_jsonl(path: impl AsRef<Path>, value: &impl Serialize) -> Result<()> {
    if let Some(parent) = path.as_ref().parent() {
        fs::create_dir_all(parent)?;
    }
    let file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(path.as_ref())?;
    let mut writer = BufWriter::new(file);
    serde_json::to_writer(&mut writer, value).map_err(AarambErrorExt::json)?;
    writer.write_all(b"\n")?;
    writer.flush()?;
    Ok(())
}

struct AarambErrorExt;

impl AarambErrorExt {
    fn json(error: serde_json::Error) -> AarambhError {
        AarambhError::Json(error)
    }
}

fn scalar_option(value: Option<&Tensor>) -> Result<Option<f64>> {
    value
        .map(|tensor| tensor.to_scalar::<f32>().map(|value| value as f64))
        .transpose()
        .map_err(Into::into)
}

fn mean(values: &[f32]) -> f64 {
    if values.is_empty() {
        0.0
    } else {
        values.iter().map(|value| *value as f64).sum::<f64>() / values.len() as f64
    }
}

fn stddev(values: &[f32], mean: f32) -> f64 {
    if values.is_empty() {
        0.0
    } else {
        (values
            .iter()
            .map(|value| (*value - mean).powi(2) as f64)
            .sum::<f64>()
            / values.len() as f64)
            .sqrt()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dataset::PromptExample;
    use crate::rollout::RolloutFinish;
    use crate::teacher_score::{TeacherBatchFeedback, TeacherScore};
    use aarambh_studio_tokenizer::{
        ASSISTANT, ASSISTANT_ID, BOS, BOS_ID, ENDOFTEXT, ENDOFTEXT_ID, PAD, PAD_ID, THINK_END,
        THINK_END_ID, THINK_START, THINK_START_ID, USER, USER_ID, Vocab,
    };
    use std::collections::HashMap;

    struct FixedRewardTeacher;

    impl TeacherScorer for FixedRewardTeacher {
        fn backend_name(&self) -> &'static str {
            "fixed_test_reward"
        }

        fn score_batch(
            &self,
            rollouts: &[StudentRollout],
            _replay: &ReplayBatch,
            signal: TeacherSignal,
        ) -> Result<TeacherBatchFeedback> {
            assert_eq!(signal, TeacherSignal::Reward);
            Ok(TeacherBatchFeedback {
                scores: rollouts
                    .iter()
                    .enumerate()
                    .map(|(index, _)| TeacherScore {
                        reward: index as f32,
                        corrected_completion: None,
                    })
                    .collect(),
                packed_logits: None,
            })
        }
    }

    fn tokenizer() -> BpeTokenizer {
        let pairs: [(&str, u32); 12] = [
            (ENDOFTEXT, ENDOFTEXT_ID),
            (PAD, PAD_ID),
            (BOS, BOS_ID),
            (THINK_START, THINK_START_ID),
            (THINK_END, THINK_END_ID),
            (USER, USER_ID),
            (ASSISTANT, ASSISTANT_ID),
            ("H", 7),
            ("e", 8),
            ("l", 9),
            ("o", 10),
            (" ", 11),
        ];
        let token_to_id = pairs
            .iter()
            .map(|(token, id)| ((*token).to_string(), *id))
            .collect::<HashMap<_, _>>();
        let mut id_to_token = vec![String::new(); 12];
        for (token, id) in pairs {
            id_to_token[id as usize] = token.to_string();
        }
        BpeTokenizer {
            vocab: Vocab {
                token_to_id,
                id_to_token,
            },
            merges: Vec::new(),
            merge_rank: HashMap::new(),
            chat_template_version: None,
        }
    }

    #[test]
    fn reward_distillation_updates_full_student_weights() {
        let device = candle_core::Device::Cpu;
        let model_config = ModelConfig {
            vocab_size: 12,
            hidden_dim: 64,
            ffn_dim: 128,
            n_layers: 1,
            n_heads: 1,
            n_kv_heads: 1,
            max_seq_len: 16,
            rope_theta: 10_000.0,
            rope_scaling: None,
            moe: None,
            attention_schedule: None,
            dsa_config: None,
            mtp: None,
            qat: None,
            norm_eps: 1e-5,
            tie_embeddings: true,
            chat_template_version: None,
        };
        let varmap = VarMap::new();
        let model = AarambhModel::new(
            &model_config,
            VarBuilder::from_varmap(&varmap, candle_core::DType::F32, &device),
        )
        .unwrap();
        let tokenizer = tokenizer();
        let prompt_tokens = tokenizer.encode("Hello").unwrap();
        let engine = InferenceEngine::new(model, tokenizer, device).unwrap();
        let prompts = PromptDataset::from_examples(vec![PromptExample {
            id: "p".into(),
            prompt: "Hello".into(),
        }])
        .unwrap();
        let output = std::env::temp_dir().join(format!(
            "aarambh_distill_full_update_{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&output);
        let train_config = TrainConfig {
            lr: 1e-2,
            batch_size: 1,
            grad_accum_steps: 1,
            max_epochs: 1,
            max_steps: 1,
            warmup_steps: 0,
            min_lr_ratio: 1.0,
            weight_decay: 0.0,
            beta1: 0.9,
            beta2: 0.95,
            epsilon: 1e-8,
            clip_grad_norm: 1.0,
            save_every_n_steps: 0,
            log_every_n_steps: 0,
            eval_steps: 0,
            seed: 42,
            checkpoint_dir: output.clone(),
        };
        let mut trainer = DistillTrainer::new(
            engine,
            varmap,
            Box::new(FixedRewardTeacher),
            prompts,
            train_config,
            DsaTrainingConfig::default(),
            DistillConfig {
                rollouts_per_prompt: 2,
                max_new_tokens: 2,
                objective: DistillObjective::Reward,
                ..DistillConfig::default()
            },
            &output,
            serde_json::json!({"test": true}),
            false,
        )
        .unwrap();
        let before = trainer
            .model()
            .named_tensors()
            .into_iter()
            .find(|(name, _)| name == "embedding.weight")
            .unwrap()
            .1
            .flatten_all()
            .unwrap()
            .to_vec1::<f32>()
            .unwrap();
        let rollouts = vec![
            StudentRollout {
                prompt_id: "p".into(),
                prompt: "Hello".into(),
                prompt_token_ids: prompt_tokens.clone(),
                completion_token_ids: vec![8, 9],
                completion_text: "el".into(),
                loss_mask: vec![true, true],
                rollout_index: 0,
                finish_reason: RolloutFinish::MaxTokens,
            },
            StudentRollout {
                prompt_id: "p".into(),
                prompt: "Hello".into(),
                prompt_token_ids: prompt_tokens,
                completion_token_ids: vec![10, 11],
                completion_text: "o ".into(),
                loss_mask: vec![true, true],
                rollout_index: 1,
                finish_reason: RolloutFinish::MaxTokens,
            },
        ];
        let metrics = trainer.train_rollouts(&rollouts, 1.0).unwrap().unwrap();
        let after = trainer
            .model()
            .named_tensors()
            .into_iter()
            .find(|(name, _)| name == "embedding.weight")
            .unwrap()
            .1
            .flatten_all()
            .unwrap()
            .to_vec1::<f32>()
            .unwrap();
        assert_eq!(metrics.step, 1);
        assert!(metrics.loss.is_finite());
        assert!(
            before
                .iter()
                .zip(after)
                .any(|(before, after)| before != &after)
        );
        let _ = fs::remove_dir_all(output);
    }

    #[test]
    fn reward_groups_reject_mixed_prompts_and_duplicate_indexes() {
        let base = StudentRollout {
            prompt_id: "a".into(),
            prompt: "Hello".into(),
            prompt_token_ids: vec![BOS_ID],
            completion_token_ids: vec![8],
            completion_text: "e".into(),
            loss_mask: vec![true],
            rollout_index: 0,
            finish_reason: RolloutFinish::MaxTokens,
        };
        let mut mixed = base.clone();
        mixed.prompt_id = "b".into();
        mixed.rollout_index = 1;
        assert!(validate_reward_groups(&[base.clone(), mixed], 2).is_err());
        assert!(validate_reward_groups(&[base.clone(), base], 2).is_err());
    }
}
