use aarambh_studio_core::AarambhError;
use aarambh_studio_inference::{GenerationOutput, ToolCall, ToolDefinition};
use serde::Serialize;
use thiserror::Error;

use crate::{
    ChainState, EvictionPolicy, ToolExchange, ToolResult, ToolResultContent, ToolResultProvider,
    ToolResultRequest,
};

/// Agent runtime result type.
pub type AgentResult<T> = std::result::Result<T, AgentError>;

#[derive(Debug, Error)]
/// Errors produced by bounded tool-chain orchestration.
pub enum AgentError {
    /// Model, tokenizer, or tensor runtime failure.
    #[error(transparent)]
    Runtime(#[from] AarambhError),
    /// Invalid chain configuration.
    #[error("agent configuration error: {0}")]
    Config(String),
    /// Invalid or mismatched caller result.
    #[error("tool result protocol error: {0}")]
    ResultProtocol(String),
    /// Scripted replay expected a different model call.
    #[error("replay mismatch for {call_id}: expected {expected:?}, model produced {actual:?}")]
    ReplayMismatch {
        /// Chain-assigned call identifier.
        call_id: String,
        /// Call expected by the replay fixture.
        expected: Box<ToolCall>,
        /// Call actually generated by the model.
        actual: Box<ToolCall>,
    },
    /// The model requested another tool after the configured call budget.
    #[error("agent reached the maximum of {limit} tool calls")]
    MaxSteps {
        /// Configured maximum tool calls.
        limit: usize,
    },
}

impl From<std::io::Error> for AgentError {
    fn from(error: std::io::Error) -> Self {
        Self::Runtime(AarambhError::Io(error))
    }
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
/// Resource and context policy for one tool-use chain.
pub struct ToolChainConfig {
    /// Maximum caller-executed tool calls.
    pub max_steps: usize,
    /// Maximum model completion tokens per decision.
    pub max_tokens_per_step: usize,
    /// Tokens kept free for the next completion.
    pub context_reserve: usize,
    /// Most recent exchanges that eviction cannot remove.
    pub keep_recent: usize,
    /// Maximum summary tokens requested from the decoder.
    pub summary_tokens: usize,
    /// Context pressure policy.
    pub eviction_policy: EvictionPolicy,
}

impl Default for ToolChainConfig {
    fn default() -> Self {
        Self {
            max_steps: 8,
            max_tokens_per_step: 256,
            context_reserve: 32,
            keep_recent: 4,
            summary_tokens: 128,
            eviction_policy: EvictionPolicy::DropOldest,
        }
    }
}

impl ToolChainConfig {
    /// Validate hard limits used to bound chain work and memory.
    pub fn validate(&self) -> AgentResult<()> {
        if !(1..=64).contains(&self.max_steps) {
            return Err(AgentError::Config(
                "max_steps must be in the range 1..=64".into(),
            ));
        }
        if self.max_tokens_per_step == 0 {
            return Err(AgentError::Config(
                "max_tokens_per_step must be greater than zero".into(),
            ));
        }
        if self.context_reserve == 0 {
            return Err(AgentError::Config(
                "context_reserve must be greater than zero".into(),
            ));
        }
        if self.keep_recent == 0 {
            return Err(AgentError::Config(
                "keep_recent must be greater than zero".into(),
            ));
        }
        if self.summary_tokens == 0 {
            return Err(AgentError::Config(
                "summary_tokens must be greater than zero".into(),
            ));
        }
        Ok(())
    }
}

/// Model-specific operations required by the generic chain runtime.
pub trait ChainDecoder {
    /// Return the model's maximum sequence length.
    fn context_limit(&self) -> usize;

    /// Encode the initial tool-aware prompt, optionally including a history summary.
    fn encode_prefix(
        &mut self,
        prompt: &str,
        tools: &[ToolDefinition],
        summary: Option<&str>,
    ) -> AgentResult<Vec<u32>>;

    /// Encode one validated caller result as a user turn ending at assistant role.
    fn encode_result(&mut self, result: &ToolResult) -> AgentResult<Vec<u32>>;

    /// Encode the metadata-only form retained after a native media turn.
    fn encode_result_metadata(&mut self, result: &ToolResult) -> AgentResult<Vec<u32>>;

    /// Produce one model decision from exact transcript ids.
    ///
    /// `pending_media` is present only for the turn immediately following a
    /// media result. Older media remains represented by transcript metadata.
    fn generate(
        &mut self,
        transcript_ids: &[u32],
        pending_media: Option<&ToolResultContent>,
        max_new_tokens: usize,
    ) -> AgentResult<GenerationOutput>;

    /// Compact evicted history into bounded text for `Summarise` eviction.
    fn summarise(
        &mut self,
        previous_summary: Option<&str>,
        evicted: &[ToolExchange],
        max_tokens: usize,
    ) -> AgentResult<String>;
}

#[derive(Debug, Clone, Default, Serialize)]
/// Aggregate counters for one chain run.
pub struct ChainMetrics {
    /// Number of model decisions.
    pub model_turns: usize,
    /// Number of externally resolved tool calls.
    pub tool_calls: usize,
    /// Total model prompt tokens.
    pub prompt_tokens: usize,
    /// Total model completion tokens.
    pub completion_tokens: usize,
    /// Number of exact exchanges evicted from active context.
    pub evictions: usize,
    /// Number of history summaries generated.
    pub summaries: usize,
    /// Number of model turns receiving native media embeddings.
    pub media_turns: usize,
}

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
/// Observable chain event for human or JSONL frontends.
pub enum ChainEvent {
    /// Model requested caller execution of a function.
    ToolCall {
        /// Request sent to the result provider.
        request: ToolResultRequest,
    },
    /// Caller supplied a validated result.
    ToolResult {
        /// Validated caller result.
        result: ToolResult,
    },
    /// Context pressure evicted a completed exchange.
    Eviction {
        /// Call id removed from exact context.
        call_id: String,
        /// Whether the removed exchange was incorporated into a summary.
        summarised: bool,
    },
    /// Model produced a final answer.
    Final {
        /// User-visible final answer.
        text: String,
    },
}

#[derive(Debug)]
/// Completed chain output with inspectable state and accounting.
pub struct ChainOutput {
    /// Final model generation.
    pub final_output: GenerationOutput,
    /// Exact retained chain state.
    pub state: ChainState,
    /// Aggregate chain metrics.
    pub metrics: ChainMetrics,
}

/// Bounded orchestrator for caller-executed long-horizon tool use.
pub struct ToolChain<D, P> {
    decoder: D,
    provider: P,
    config: ToolChainConfig,
}

impl<D: ChainDecoder, P: ToolResultProvider> ToolChain<D, P> {
    /// Build a chain from a model decoder, caller result provider, and limits.
    pub fn new(decoder: D, provider: P, config: ToolChainConfig) -> AgentResult<Self> {
        config.validate()?;
        if config.context_reserve >= decoder.context_limit() {
            return Err(AgentError::Config(
                "context_reserve must be smaller than model context length".into(),
            ));
        }
        Ok(Self {
            decoder,
            provider,
            config,
        })
    }

    /// Run a chain to a final answer without event callbacks.
    pub fn run(
        &mut self,
        prompt: impl Into<String>,
        tools: Vec<ToolDefinition>,
    ) -> AgentResult<ChainOutput> {
        self.run_with_callback(prompt, tools, |_| Ok(()))
    }

    /// Run a chain and emit deterministic lifecycle events.
    pub fn run_with_callback<F>(
        &mut self,
        prompt: impl Into<String>,
        tools: Vec<ToolDefinition>,
        mut on_event: F,
    ) -> AgentResult<ChainOutput>
    where
        F: FnMut(&ChainEvent) -> AgentResult<()>,
    {
        let prompt = prompt.into();
        if prompt.trim().is_empty() {
            return Err(AgentError::Config("prompt must not be empty".into()));
        }
        if tools.is_empty() {
            return Err(AgentError::Config(
                "agent requires at least one tool".into(),
            ));
        }
        let prefix = self.decoder.encode_prefix(&prompt, &tools, None)?;
        let mut state = ChainState::new(prompt, tools, prefix);
        let mut metrics = ChainMetrics::default();
        let mut has_pending_media = false;

        loop {
            self.relieve_context_pressure(&mut state, &mut metrics, &mut on_event)?;
            let transcript = state.transcript_token_ids();
            let media = has_pending_media
                .then(|| state.exchanges().last())
                .flatten()
                .and_then(|exchange| exchange.result.media_content());
            if media.is_some() {
                metrics.media_turns += 1;
            }
            let output =
                self.decoder
                    .generate(&transcript, media, self.config.max_tokens_per_step)?;
            if has_pending_media {
                let result = state
                    .exchanges()
                    .last()
                    .expect("pending media requires a completed exchange")
                    .result
                    .clone();
                let metadata_ids = self.decoder.encode_result_metadata(&result)?;
                state
                    .last_exchange_mut()
                    .expect("pending media requires a completed exchange")
                    .result_token_ids = metadata_ids;
            }
            has_pending_media = false;
            metrics.model_turns += 1;
            metrics.prompt_tokens += output.usage.prompt_tokens;
            metrics.completion_tokens += output.usage.completion_tokens;

            let Some(call) = output.tool_call.clone() else {
                self.provider.finish()?;
                on_event(&ChainEvent::Final {
                    text: output.text.clone(),
                })?;
                return Ok(ChainOutput {
                    final_output: output,
                    state,
                    metrics,
                });
            };
            if metrics.tool_calls >= self.config.max_steps {
                return Err(AgentError::MaxSteps {
                    limit: self.config.max_steps,
                });
            }

            let request = ToolResultRequest {
                call_id: format!("call_{:04}", metrics.tool_calls + 1),
                call,
            };
            on_event(&ChainEvent::ToolCall {
                request: request.clone(),
            })?;
            let result = self.provider.next_result(&request)?;
            result.validate_for(&request.call_id)?;
            on_event(&ChainEvent::ToolResult {
                result: result.clone(),
            })?;
            let result_token_ids = self.decoder.encode_result(&result)?;
            state.push(ToolExchange {
                request,
                result,
                call_token_ids: output.token_ids,
                result_token_ids,
            });
            metrics.tool_calls += 1;
            if state
                .exchanges()
                .last()
                .is_some_and(|exchange| exchange.result.media_content().is_some())
            {
                has_pending_media = true;
            }
        }
    }

    fn relieve_context_pressure<F>(
        &mut self,
        state: &mut ChainState,
        metrics: &mut ChainMetrics,
        on_event: &mut F,
    ) -> AgentResult<()>
    where
        F: FnMut(&ChainEvent) -> AgentResult<()>,
    {
        let usable = self
            .decoder
            .context_limit()
            .saturating_sub(self.config.context_reserve);
        // Phase 52: under `EvictionPolicy::Reject` the chain refuses to proceed
        // rather than silently drop context — the mandatory default for safety-
        // or execution-sensitive sessions. Check this before evicting anything.
        if self.config.eviction_policy == EvictionPolicy::Reject
            && state.transcript_token_ids().len() > usable
        {
            return Err(AgentError::Config(format!(
                "eviction policy is `Reject`: chain transcript of {} tokens exceeds \
                 usable context {usable}; refusing to drop context rather than proceed \
                 with an incomplete picture",
                state.transcript_token_ids().len()
            )));
        }
        while state.transcript_token_ids().len() > usable {
            if state.exchanges().len() <= self.config.keep_recent {
                return Err(AgentError::Config(format!(
                    "active prompt and {} protected exchanges exceed usable context {usable}",
                    state.exchanges().len()
                )));
            }
            let evicted = state
                .pop_oldest()
                .expect("exchange length was checked before eviction");
            let summarised = self.config.eviction_policy == EvictionPolicy::Summarise;
            let call_id = evicted.request.call_id.clone();
            if summarised {
                let summary = self.decoder.summarise(
                    state.summary(),
                    std::slice::from_ref(&evicted),
                    self.config.summary_tokens,
                )?;
                let prefix =
                    self.decoder
                        .encode_prefix(state.prompt(), state.tools(), Some(&summary))?;
                state.replace_prefix(summary, prefix);
                metrics.summaries += 1;
            }
            metrics.evictions += 1;
            on_event(&ChainEvent::Eviction {
                call_id,
                summarised,
            })?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::collections::VecDeque;

    use aarambh_studio_inference::{FinishReason, GenerationUsage, ToolCall, ToolDefinition};
    use serde_json::json;

    use super::*;
    use crate::{ReplayEntry, ReplayResultProvider, ToolResultContent, ToolResultStatus};

    struct FakeDecoder {
        outputs: VecDeque<GenerationOutput>,
        context_limit: usize,
    }

    impl ChainDecoder for FakeDecoder {
        fn context_limit(&self) -> usize {
            self.context_limit
        }

        fn encode_prefix(
            &mut self,
            _prompt: &str,
            _tools: &[ToolDefinition],
            summary: Option<&str>,
        ) -> AgentResult<Vec<u32>> {
            Ok(if summary.is_some() {
                vec![1, 2, 3]
            } else {
                vec![1, 2]
            })
        }

        fn encode_result(&mut self, _result: &ToolResult) -> AgentResult<Vec<u32>> {
            Ok(vec![8, 9])
        }

        fn encode_result_metadata(&mut self, _result: &ToolResult) -> AgentResult<Vec<u32>> {
            Ok(vec![8])
        }

        fn generate(
            &mut self,
            _transcript_ids: &[u32],
            _pending_media: Option<&ToolResultContent>,
            _max_new_tokens: usize,
        ) -> AgentResult<GenerationOutput> {
            self.outputs
                .pop_front()
                .ok_or_else(|| AgentError::Config("fake output exhausted".into()))
        }

        fn summarise(
            &mut self,
            _previous_summary: Option<&str>,
            _evicted: &[ToolExchange],
            _max_tokens: usize,
        ) -> AgentResult<String> {
            Ok("summary".into())
        }
    }

    fn call() -> ToolCall {
        ToolCall {
            name: "lookup".into(),
            arguments: json!({"key": "value"}),
        }
    }

    fn output(tool_call: Option<ToolCall>, text: &str) -> GenerationOutput {
        GenerationOutput {
            text: text.into(),
            raw_text: text.into(),
            thinking_text: String::new(),
            answer_text: text.into(),
            token_ids: vec![4, 5],
            thinking_token_ids: Vec::new(),
            answer_token_ids: vec![4, 5],
            thinking_tokens: 0,
            finish_reason: if tool_call.is_some() {
                FinishReason::ToolCall
            } else {
                FinishReason::EosToken
            },
            steps: Vec::new(),
            speculative_stats: None,
            tool_call,
            usage: GenerationUsage {
                prompt_tokens: 2,
                completion_tokens: 2,
                total_tokens: 4,
            },
        }
    }

    fn tools() -> Vec<ToolDefinition> {
        vec![ToolDefinition {
            name: "lookup".into(),
            description: String::new(),
            parameters: json!({
                "type": "object",
                "properties": {"key": {"type": "string"}},
                "required": ["key"]
            }),
        }]
    }

    fn replay(count: usize) -> ReplayResultProvider {
        ReplayResultProvider::new(
            (1..=count)
                .map(|index| ReplayEntry {
                    expected_call: Some(call()),
                    result: ToolResult {
                        call_id: format!("call_{index:04}"),
                        status: ToolResultStatus::Ok,
                        content: Some(ToolResultContent::Text {
                            text: "result".into(),
                        }),
                        error: None,
                    },
                })
                .collect(),
        )
        .unwrap()
    }

    #[test]
    fn chain_stops_on_normal_response() {
        let decoder = FakeDecoder {
            outputs: [output(Some(call()), ""), output(None, "done")].into(),
            context_limit: 64,
        };
        let mut chain = ToolChain::new(decoder, replay(1), ToolChainConfig::default()).unwrap();
        let result = chain.run("find it", tools()).unwrap();
        assert_eq!(result.final_output.text, "done");
        assert_eq!(result.metrics.tool_calls, 1);
        assert_eq!(result.state.exchanges().len(), 1);
    }

    #[test]
    fn chain_enforces_tool_call_budget() {
        let decoder = FakeDecoder {
            outputs: [output(Some(call()), ""), output(Some(call()), "")].into(),
            context_limit: 64,
        };
        let config = ToolChainConfig {
            max_steps: 1,
            ..ToolChainConfig::default()
        };
        let mut chain = ToolChain::new(decoder, replay(1), config).unwrap();
        assert!(matches!(
            chain.run("find it", tools()),
            Err(AgentError::MaxSteps { limit: 1 })
        ));
    }

    #[test]
    fn context_pressure_evicts_oldest_exchange() {
        let decoder = FakeDecoder {
            outputs: [
                output(Some(call()), ""),
                output(Some(call()), ""),
                output(None, "done"),
            ]
            .into(),
            context_limit: 10,
        };
        let config = ToolChainConfig {
            context_reserve: 2,
            keep_recent: 1,
            ..ToolChainConfig::default()
        };
        let mut chain = ToolChain::new(decoder, replay(2), config).unwrap();
        let result = chain.run("find it", tools()).unwrap();
        assert_eq!(result.metrics.evictions, 1);
        assert_eq!(result.state.exchanges().len(), 1);
    }

    #[test]
    fn context_pressure_reject_refuses_rather_than_silently_dropping() {
        // Phase 52: under `EvictionPolicy::Reject` a chain that would exceed
        // its usable context must error loudly instead of silently evicting a
        // turn — the mandatory default for safety-/execution-sensitive sessions.
        let decoder = FakeDecoder {
            outputs: [
                output(Some(call()), ""),
                output(Some(call()), ""),
                output(None, "done"),
            ]
            .into(),
            context_limit: 10,
        };
        let config = ToolChainConfig {
            context_reserve: 2,
            keep_recent: 1,
            eviction_policy: EvictionPolicy::Reject,
            ..ToolChainConfig::default()
        };
        let mut chain = ToolChain::new(decoder, replay(2), config).unwrap();
        let err = chain.run("find it", tools()).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("Reject"),
            "error must name the Reject policy, got: {msg}"
        );
        assert!(
            msg.contains("refusing to drop context"),
            "error must state the refusal, got: {msg}"
        );
    }

    #[test]
    fn eviction_policy_maps_onto_canonical_context_truncation_policy() {
        // Phase 52: the agent-crate `EvictionPolicy` maps one-to-one onto the
        // canonical `ContextTruncationPolicy` defined in the inference crate.
        use aarambh_studio_inference::ContextTruncationPolicy;
        assert_eq!(
            ContextTruncationPolicy::from(EvictionPolicy::DropOldest),
            ContextTruncationPolicy::SlidingWindow
        );
        assert_eq!(
            ContextTruncationPolicy::from(EvictionPolicy::Summarise),
            ContextTruncationPolicy::Summarize
        );
        assert_eq!(
            ContextTruncationPolicy::from(EvictionPolicy::Reject),
            ContextTruncationPolicy::Reject
        );
    }
}
